;;; Problem file: all-out-p02.pddl
(define (problem all-out-p02)
  (:domain all-out)
  (:objects
    light1 light2 light3 light4 light5 light6 light7 light8 light9 light10 light11 light12
 light13 light14 light15 light16
  )
  (:init
(not(light-on light1))  (not(light-on light2))  
(not(light-on light3))  (not(light-on light4))
(not(light-on light5))  (not(light-on light6))  
(not(light-on light7))  (not(light-on light8))
(not(light-on light9))  (not(light-on light10)) 
(not(light-on light11)) (not(light-on light12))
(not(light-on light13)) (not(light-on light14)) 
(not(light-on light15)) (not(light-on light16))

(neighbor light1 light2) (neighbor light1 light5)
(neighbor light2 light1) (neighbor light2 light3) 
(neighbor light2 light6)
(neighbor light3 light2) (neighbor light3 light4) 
(neighbor light3 light7)
(neighbor light4 light3) (neighbor light4 light8)
(neighbor light5 light1) (neighbor light5 light6) 
(neighbor light5 light9)
(neighbor light6 light2) (neighbor light6 light5) 
(neighbor light6 light7) (neighbor light6 light10)
(neighbor light7 light3) (neighbor light7 light6) 
(neighbor light7 light8) (neighbor light7 light11)
(neighbor light8 light4) (neighbor light8 light7) 
(neighbor light8 light12)
(neighbor light9 light5) (neighbor light9 light10) 
(neighbor light9 light13)
(neighbor light10 light9) (neighbor light10 light6) 
(neighbor light10 light11) (neighbor light10 light14)
(neighbor light11 light7) (neighbor light11 light10) 
(neighbor light11 light12) (neighbor light11 light15)
(neighbor light12 light8) (neighbor light12 light11) 
(neighbor light12 light16)
(neighbor light13 light9) (neighbor light13 light14)
(neighbor light14 light13) (neighbor light14 light10) 
(neighbor light14 light15)
(neighbor light15 light14) (neighbor light15 light11) 
(neighbor light15 light16)
(neighbor light16 light15) (neighbor light16 light12)

)
(:goal (forall (?x) (not (light-on ?x)))))